# Generated by Django 4.2.4 on 2023-12-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowYourCallerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='phone_number',
            new_name='number',
        ),
    ]
