# Generated by Django 4.2.4 on 2023-12-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowYourCallerApp', '0002_rename_phone_number_phonenumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
